name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Run test build
      run: npm run build
    - name: Run unit test
      run: npm test
    - name: Run E2E test
      run: npm run test:e2e:ci
    - uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v1
      with:
        name: videos
        path: cypress/videos
      env:
        CI: true
